language: php
php:
  - 7.3.5
services:
  - postgresql
env:
  - DATABASE_URL="pgsql://$db_user:$db_password@127.0.0.1:5432/$db_name"
before_script:
  - psql -c "CREATE DATABASE $db_name;" -U postgres
  - psql -c "CREATE USER $db_name WITH PASSWORD '$db_password';" -U postgres
scripts:
  - composer install
  - php bin/console doctrine:schema:update --force
  - php bin/console doctrine:fixtures:load -n
  - php bin/phpunit