language: php
php:
  - 7.3.5
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE $db_name;" -U postgres
  - psql -c "CREATE USER $db_name WITH PASSWORD '$db_password';" -U postgres
scripts:
  - composer install
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load -n --env=test
  - php bin/phpunit