language: php
sudo: false

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit

env:
  global:
    - SYMFONY_PHPUNIT_DIR=./bin/.phpunit
    - SYMFONY_DEPRECATIONS_HELPER=0
    - ACTION="install"

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3.5
      env: SYMFONY="5.0.*"
           ACTION="update"
    # 'php: nightly' is PHP 8.0
    - php: 7.4snapshot
  allow_failures:
    - php: 7.4snapshot

install:
  - composer install
  - ./bin/phpunit install

script:
  # - ./bin/phpunit
  # # this checks that the source code follows the Symfony Code Syntax rules
  # - '[[ "$TRAVIS_PHP_VERSION" == "7.4snapshot" ]] || ./vendor/bin/php-cs-fixer fix --diff --dry-run -v'
  # # this checks that the YAML config files contain no syntax errors
  # - ./bin/console lint:yaml config --parse-tags
  # # this checks that the Twig template files contain no syntax errors
  # - ./bin/console lint:twig templates --env=prod
  # # this checks that the XLIFF translations contain no syntax errors
  # - ./bin/console lint:xliff translations
  # # this checks that arguments injected into services match type declarations
  # - ./bin/console lint:container
  # # TODO: replace the old security checker by the new checker provided by the 'symfony' binary
  # # this checks that the application doesn't use dependencies with known security vulnerabilities
  # #- ./bin/console security:check
  # # this checks that Doctrine's mapping configurations are valid
  # - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
  # #  Fail CI if the repo is in a dirty state after building assets (only for current release ie install)
  # #-  if [[ "$ACTION" == "install" ]]; then yarn install && yarn encore production && git add --all && git diff --staged --exit-code; fi